# Core server binaries
usr/bin/comp_err
usr/bin/ps_mysqld_helper
usr/bin/ibd2sdi
usr/bin/clustercheck
usr/bin/pyclustercheck
usr/bin/innochecksum
usr/bin/my_print_defaults
usr/bin/myisamchk
usr/bin/myisamlog
usr/bin/myisampack
usr/bin/mysql_secure_installation
usr/bin/mysql_tzinfo_to_sql
usr/bin/mysqlbinlog
usr/bin/mysqld_multi
usr/bin/mysqld_safe
usr/bin/mysqltest
usr/bin/perror
usr/bin/pxc_extra
usr/bin/mysql_keyring_encryption_test
usr/bin/mysql_migrate_keyring
usr/bin/mysql-systemd
usr/sbin/mysqld

# state transfer
usr/bin/wsrep_sst_common
usr/bin/wsrep_sst_xtrabackup-v2
# usr/bin/wsrep_sst_rsync
#usr/bin/wsrep_sst_upgrade

# Galera provider
libgalera_smm.so usr/lib/galera4

# plugins
usr/lib/mysql/plugin/*.so

# man pages
usr/share/man/man1/ibd2sdi.1
usr/share/man/man1/myisamchk.1
usr/share/man/man1/myisamlog.1
usr/share/man/man1/myisampack.1
usr/share/man/man1/my_print_defaults.1
usr/share/man/man1/mysqlbinlog.1
usr/share/man/man1/mysqld_multi.1
usr/share/man/man1/mysqld_safe.1
usr/share/man/man1/mysql_secure_installation.1
usr/share/man/man1/perror.1
usr/share/man/man1/innochecksum.1
usr/share/man/man1/mysql_tzinfo_to_sql.1
usr/share/man/man1/mysql.server.1
usr/share/man/man1/comp_err.1
usr/share/man/man1/mysqlman.1
usr/share/man/man8/mysqld.8

# data files
usr/share/mysql

# private shared libs
usr/lib/mysql/private/libprotobuf-lite.so.*
usr/lib/mysql/private/libprotobuf.so.*
usr/lib/mysql/private/libabsl_*.so
# private data files
usr/lib/mysql/private/icudt77l/*.icu
usr/lib/mysql/private/icudt77l/brkitr/*
usr/lib/mysql/private/libicui18n.so.*
usr/lib/mysql/private/libicustubdata.so.*
usr/lib/mysql/private/libicuuc.so.*
