debian/additions/mysql-systemd-start usr/share/mysql/
debian/additions/mysql.cnf etc/mysql/
debian/additions/mysql.conf.d etc/mysql/
debian/additions/source_mysql-5.7.py usr/share/apport/package-hooks/
etc/apparmor.d/usr.sbin.mysqld
etc/mysql/debian-start
usr/bin/lz4_decompress usr/lib/mysql/
usr/bin/myisamchk
usr/bin/myisamlog
usr/bin/myisampack
usr/bin/mysql_plugin
usr/bin/mysql_secure_installation
usr/bin/mysql_ssl_rsa_setup
usr/bin/mysql_tzinfo_to_sql
usr/bin/mysqlbinlog
usr/bin/mysqld_multi
usr/bin/mysqld_safe
usr/bin/perror
usr/bin/replace
usr/bin/resolve_stack_dump usr/lib/mysql/
usr/bin/resolveip
usr/bin/zlib_decompress usr/lib/mysql/
usr/lib/mysql/plugin/adt_null.so
usr/lib/mysql/plugin/auth_socket.so
usr/lib/mysql/plugin/innodb_engine.so
usr/lib/mysql/plugin/keyring_file.so
usr/lib/mysql/plugin/libmemcached.so
usr/lib/mysql/plugin/libpluginmecab.so
usr/lib/mysql/plugin/locking_service.so
usr/lib/mysql/plugin/mypluglib.so
usr/lib/mysql/plugin/mysql_no_login.so
usr/lib/mysql/plugin/rewriter.so
usr/lib/mysql/plugin/semisync_master.so
usr/lib/mysql/plugin/semisync_slave.so
usr/lib/mysql/plugin/validate_password.so
usr/lib/mysql/plugin/version_token.so
usr/share/doc/mysql-server-5.7/
usr/share/mysql/debian-start.inc.sh
usr/share/mysql/debian_create_root_user.sql
usr/share/mysql/docs/INFO_BIN
usr/share/mysql/docs/INFO_SRC
usr/share/mysql/echo_stderr
usr/share/mysql/errmsg-utf8.txt
usr/share/mysql/install_rewriter.sql
usr/share/mysql/mysql_sys_schema.sql
usr/share/mysql/mysql_test_data_timezone.sql
usr/share/mysql/mysqld_multi.server
usr/share/mysql/uninstall_rewriter.sql
