// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mysqlx_sql.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "mysqlx_sql.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)

namespace Mysqlx {
namespace Sql {

void protobuf_ShutdownFile_mysqlx_5fsql_2eproto() {
  delete StmtExecute::default_instance_;
  delete StmtExecute::_default_namespace__;
  delete StmtExecuteOk::default_instance_;
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
void protobuf_AddDesc_mysqlx_5fsql_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#else
void protobuf_AddDesc_mysqlx_5fsql_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#endif
  ::Mysqlx::Datatypes::protobuf_AddDesc_mysqlx_5fdatatypes_2eproto();
  StmtExecute::_default_namespace__ =
      new ::std::string("sql", 3);
  StmtExecute::default_instance_ = new StmtExecute();
  StmtExecuteOk::default_instance_ = new StmtExecuteOk();
  StmtExecute::default_instance_->InitAsDefaultInstance();
  StmtExecuteOk::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_mysqlx_5fsql_2eproto);
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_mysqlx_5fsql_2eproto_once_);
void protobuf_AddDesc_mysqlx_5fsql_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_mysqlx_5fsql_2eproto_once_,
                 &protobuf_AddDesc_mysqlx_5fsql_2eproto_impl);
}
#else
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_mysqlx_5fsql_2eproto {
  StaticDescriptorInitializer_mysqlx_5fsql_2eproto() {
    protobuf_AddDesc_mysqlx_5fsql_2eproto();
  }
} static_descriptor_initializer_mysqlx_5fsql_2eproto_;
#endif

// ===================================================================

::std::string* StmtExecute::_default_namespace__ = NULL;
#ifndef _MSC_VER
const int StmtExecute::kNamespaceFieldNumber;
const int StmtExecute::kStmtFieldNumber;
const int StmtExecute::kArgsFieldNumber;
const int StmtExecute::kCompactMetadataFieldNumber;
#endif  // !_MSC_VER

StmtExecute::StmtExecute()
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Mysqlx.Sql.StmtExecute)
}

void StmtExecute::InitAsDefaultInstance() {
}

StmtExecute::StmtExecute(const StmtExecute& from)
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Mysqlx.Sql.StmtExecute)
}

void StmtExecute::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  namespace__ = const_cast< ::std::string*>(_default_namespace__);
  stmt_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  compact_metadata_ = false;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

StmtExecute::~StmtExecute() {
  // @@protoc_insertion_point(destructor:Mysqlx.Sql.StmtExecute)
  SharedDtor();
}

void StmtExecute::SharedDtor() {
  if (namespace__ != _default_namespace__) {
    delete namespace__;
  }
  if (stmt_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete stmt_;
  }
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void StmtExecute::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const StmtExecute& StmtExecute::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_mysqlx_5fsql_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_mysqlx_5fsql_2eproto();
#endif
  return *default_instance_;
}

StmtExecute* StmtExecute::default_instance_ = NULL;

StmtExecute* StmtExecute::New() const {
  return new StmtExecute;
}

void StmtExecute::Clear() {
  if (_has_bits_[0 / 32] & 11) {
    if (has_namespace_()) {
      if (namespace__ != _default_namespace__) {
        namespace__->assign(*_default_namespace__);
      }
    }
    if (has_stmt()) {
      if (stmt_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        stmt_->clear();
      }
    }
    compact_metadata_ = false;
  }
  args_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->clear();
}

bool StmtExecute::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::io::StringOutputStream unknown_fields_string(
      mutable_unknown_fields());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_string);
  // @@protoc_insertion_point(parse_start:Mysqlx.Sql.StmtExecute)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required bytes stmt = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_stmt()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_args;
        break;
      }

      // repeated .Mysqlx.Datatypes.Any args = 2;
      case 2: {
        if (tag == 18) {
         parse_args:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_args()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_args;
        if (input->ExpectTag(26)) goto parse_namespace;
        break;
      }

      // optional string namespace = 3 [default = "sql"];
      case 3: {
        if (tag == 26) {
         parse_namespace:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_namespace_()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_compact_metadata;
        break;
      }

      // optional bool compact_metadata = 4 [default = false];
      case 4: {
        if (tag == 32) {
         parse_compact_metadata:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &compact_metadata_)));
          set_has_compact_metadata();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Mysqlx.Sql.StmtExecute)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Mysqlx.Sql.StmtExecute)
  return false;
#undef DO_
}

void StmtExecute::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Mysqlx.Sql.StmtExecute)
  // required bytes stmt = 1;
  if (has_stmt()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      1, this->stmt(), output);
  }

  // repeated .Mysqlx.Datatypes.Any args = 2;
  for (int i = 0; i < this->args_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      2, this->args(i), output);
  }

  // optional string namespace = 3 [default = "sql"];
  if (has_namespace_()) {
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->namespace_(), output);
  }

  // optional bool compact_metadata = 4 [default = false];
  if (has_compact_metadata()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(4, this->compact_metadata(), output);
  }

  output->WriteRaw(unknown_fields().data(),
                   unknown_fields().size());
  // @@protoc_insertion_point(serialize_end:Mysqlx.Sql.StmtExecute)
}

int StmtExecute::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional string namespace = 3 [default = "sql"];
    if (has_namespace_()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->namespace_());
    }

    // required bytes stmt = 1;
    if (has_stmt()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->stmt());
    }

    // optional bool compact_metadata = 4 [default = false];
    if (has_compact_metadata()) {
      total_size += 1 + 1;
    }

  }
  // repeated .Mysqlx.Datatypes.Any args = 2;
  total_size += 1 * this->args_size();
  for (int i = 0; i < this->args_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->args(i));
  }

  total_size += unknown_fields().size();

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void StmtExecute::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const StmtExecute*>(&from));
}

void StmtExecute::MergeFrom(const StmtExecute& from) {
  GOOGLE_CHECK_NE(&from, this);
  args_.MergeFrom(from.args_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_namespace_()) {
      set_namespace_(from.namespace_());
    }
    if (from.has_stmt()) {
      set_stmt(from.stmt());
    }
    if (from.has_compact_metadata()) {
      set_compact_metadata(from.compact_metadata());
    }
  }
  mutable_unknown_fields()->append(from.unknown_fields());
}

void StmtExecute::CopyFrom(const StmtExecute& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool StmtExecute::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000002) != 0x00000002) return false;

  if (!::google::protobuf::internal::AllAreInitialized(this->args())) return false;
  return true;
}

void StmtExecute::Swap(StmtExecute* other) {
  if (other != this) {
    std::swap(namespace__, other->namespace__);
    std::swap(stmt_, other->stmt_);
    args_.Swap(&other->args_);
    std::swap(compact_metadata_, other->compact_metadata_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.swap(other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::std::string StmtExecute::GetTypeName() const {
  return "Mysqlx.Sql.StmtExecute";
}


// ===================================================================

#ifndef _MSC_VER
#endif  // !_MSC_VER

StmtExecuteOk::StmtExecuteOk()
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Mysqlx.Sql.StmtExecuteOk)
}

void StmtExecuteOk::InitAsDefaultInstance() {
}

StmtExecuteOk::StmtExecuteOk(const StmtExecuteOk& from)
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Mysqlx.Sql.StmtExecuteOk)
}

void StmtExecuteOk::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

StmtExecuteOk::~StmtExecuteOk() {
  // @@protoc_insertion_point(destructor:Mysqlx.Sql.StmtExecuteOk)
  SharedDtor();
}

void StmtExecuteOk::SharedDtor() {
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void StmtExecuteOk::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const StmtExecuteOk& StmtExecuteOk::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_mysqlx_5fsql_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_mysqlx_5fsql_2eproto();
#endif
  return *default_instance_;
}

StmtExecuteOk* StmtExecuteOk::default_instance_ = NULL;

StmtExecuteOk* StmtExecuteOk::New() const {
  return new StmtExecuteOk;
}

void StmtExecuteOk::Clear() {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->clear();
}

bool StmtExecuteOk::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::io::StringOutputStream unknown_fields_string(
      mutable_unknown_fields());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_string);
  // @@protoc_insertion_point(parse_start:Mysqlx.Sql.StmtExecuteOk)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0 ||
        ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
        ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormatLite::SkipField(
        input, tag, &unknown_fields_stream));
  }
success:
  // @@protoc_insertion_point(parse_success:Mysqlx.Sql.StmtExecuteOk)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Mysqlx.Sql.StmtExecuteOk)
  return false;
#undef DO_
}

void StmtExecuteOk::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Mysqlx.Sql.StmtExecuteOk)
  output->WriteRaw(unknown_fields().data(),
                   unknown_fields().size());
  // @@protoc_insertion_point(serialize_end:Mysqlx.Sql.StmtExecuteOk)
}

int StmtExecuteOk::ByteSize() const {
  int total_size = 0;

  total_size += unknown_fields().size();

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void StmtExecuteOk::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const StmtExecuteOk*>(&from));
}

void StmtExecuteOk::MergeFrom(const StmtExecuteOk& from) {
  GOOGLE_CHECK_NE(&from, this);
  mutable_unknown_fields()->append(from.unknown_fields());
}

void StmtExecuteOk::CopyFrom(const StmtExecuteOk& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool StmtExecuteOk::IsInitialized() const {

  return true;
}

void StmtExecuteOk::Swap(StmtExecuteOk* other) {
  if (other != this) {
    _unknown_fields_.swap(other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::std::string StmtExecuteOk::GetTypeName() const {
  return "Mysqlx.Sql.StmtExecuteOk";
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Sql
}  // namespace Mysqlx

// @@protoc_insertion_point(global_scope)
