// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mysqlx_connection.proto

#ifndef PROTOBUF_mysqlx_5fconnection_2eproto__INCLUDED
#define PROTOBUF_mysqlx_5fconnection_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include "mysqlx_datatypes.pb.h"
// @@protoc_insertion_point(includes)

namespace Mysqlx {
namespace Connection {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_mysqlx_5fconnection_2eproto();
void protobuf_AssignDesc_mysqlx_5fconnection_2eproto();
void protobuf_ShutdownFile_mysqlx_5fconnection_2eproto();

class Capability;
class Capabilities;
class CapabilitiesGet;
class CapabilitiesSet;
class Close;

// ===================================================================

class Capability : public ::google::protobuf::MessageLite {
 public:
  Capability();
  virtual ~Capability();

  Capability(const Capability& from);

  inline Capability& operator=(const Capability& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const Capability& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const Capability* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(Capability* other);

  // implements Message ----------------------------------------------

  Capability* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const Capability& from);
  void MergeFrom(const Capability& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string name = 1;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // required .Mysqlx.Datatypes.Any value = 2;
  inline bool has_value() const;
  inline void clear_value();
  static const int kValueFieldNumber = 2;
  inline const ::Mysqlx::Datatypes::Any& value() const;
  inline ::Mysqlx::Datatypes::Any* mutable_value();
  inline ::Mysqlx::Datatypes::Any* release_value();
  inline void set_allocated_value(::Mysqlx::Datatypes::Any* value);

  // @@protoc_insertion_point(class_scope:Mysqlx.Connection.Capability)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_value();
  inline void clear_has_value();

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* name_;
  ::Mysqlx::Datatypes::Any* value_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_mysqlx_5fconnection_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_mysqlx_5fconnection_2eproto();
  #endif
  friend void protobuf_AssignDesc_mysqlx_5fconnection_2eproto();
  friend void protobuf_ShutdownFile_mysqlx_5fconnection_2eproto();

  void InitAsDefaultInstance();
  static Capability* default_instance_;
};
// -------------------------------------------------------------------

class Capabilities : public ::google::protobuf::MessageLite {
 public:
  Capabilities();
  virtual ~Capabilities();

  Capabilities(const Capabilities& from);

  inline Capabilities& operator=(const Capabilities& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const Capabilities& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const Capabilities* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(Capabilities* other);

  // implements Message ----------------------------------------------

  Capabilities* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const Capabilities& from);
  void MergeFrom(const Capabilities& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .Mysqlx.Connection.Capability capabilities = 1;
  inline int capabilities_size() const;
  inline void clear_capabilities();
  static const int kCapabilitiesFieldNumber = 1;
  inline const ::Mysqlx::Connection::Capability& capabilities(int index) const;
  inline ::Mysqlx::Connection::Capability* mutable_capabilities(int index);
  inline ::Mysqlx::Connection::Capability* add_capabilities();
  inline const ::google::protobuf::RepeatedPtrField< ::Mysqlx::Connection::Capability >&
      capabilities() const;
  inline ::google::protobuf::RepeatedPtrField< ::Mysqlx::Connection::Capability >*
      mutable_capabilities();

  // @@protoc_insertion_point(class_scope:Mysqlx.Connection.Capabilities)
 private:

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::Mysqlx::Connection::Capability > capabilities_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_mysqlx_5fconnection_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_mysqlx_5fconnection_2eproto();
  #endif
  friend void protobuf_AssignDesc_mysqlx_5fconnection_2eproto();
  friend void protobuf_ShutdownFile_mysqlx_5fconnection_2eproto();

  void InitAsDefaultInstance();
  static Capabilities* default_instance_;
};
// -------------------------------------------------------------------

class CapabilitiesGet : public ::google::protobuf::MessageLite {
 public:
  CapabilitiesGet();
  virtual ~CapabilitiesGet();

  CapabilitiesGet(const CapabilitiesGet& from);

  inline CapabilitiesGet& operator=(const CapabilitiesGet& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const CapabilitiesGet& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const CapabilitiesGet* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(CapabilitiesGet* other);

  // implements Message ----------------------------------------------

  CapabilitiesGet* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const CapabilitiesGet& from);
  void MergeFrom(const CapabilitiesGet& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:Mysqlx.Connection.CapabilitiesGet)
 private:

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_mysqlx_5fconnection_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_mysqlx_5fconnection_2eproto();
  #endif
  friend void protobuf_AssignDesc_mysqlx_5fconnection_2eproto();
  friend void protobuf_ShutdownFile_mysqlx_5fconnection_2eproto();

  void InitAsDefaultInstance();
  static CapabilitiesGet* default_instance_;
};
// -------------------------------------------------------------------

class CapabilitiesSet : public ::google::protobuf::MessageLite {
 public:
  CapabilitiesSet();
  virtual ~CapabilitiesSet();

  CapabilitiesSet(const CapabilitiesSet& from);

  inline CapabilitiesSet& operator=(const CapabilitiesSet& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const CapabilitiesSet& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const CapabilitiesSet* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(CapabilitiesSet* other);

  // implements Message ----------------------------------------------

  CapabilitiesSet* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const CapabilitiesSet& from);
  void MergeFrom(const CapabilitiesSet& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .Mysqlx.Connection.Capabilities capabilities = 1;
  inline bool has_capabilities() const;
  inline void clear_capabilities();
  static const int kCapabilitiesFieldNumber = 1;
  inline const ::Mysqlx::Connection::Capabilities& capabilities() const;
  inline ::Mysqlx::Connection::Capabilities* mutable_capabilities();
  inline ::Mysqlx::Connection::Capabilities* release_capabilities();
  inline void set_allocated_capabilities(::Mysqlx::Connection::Capabilities* capabilities);

  // @@protoc_insertion_point(class_scope:Mysqlx.Connection.CapabilitiesSet)
 private:
  inline void set_has_capabilities();
  inline void clear_has_capabilities();

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::Mysqlx::Connection::Capabilities* capabilities_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_mysqlx_5fconnection_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_mysqlx_5fconnection_2eproto();
  #endif
  friend void protobuf_AssignDesc_mysqlx_5fconnection_2eproto();
  friend void protobuf_ShutdownFile_mysqlx_5fconnection_2eproto();

  void InitAsDefaultInstance();
  static CapabilitiesSet* default_instance_;
};
// -------------------------------------------------------------------

class Close : public ::google::protobuf::MessageLite {
 public:
  Close();
  virtual ~Close();

  Close(const Close& from);

  inline Close& operator=(const Close& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const Close& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const Close* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(Close* other);

  // implements Message ----------------------------------------------

  Close* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const Close& from);
  void MergeFrom(const Close& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:Mysqlx.Connection.Close)
 private:

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_mysqlx_5fconnection_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_mysqlx_5fconnection_2eproto();
  #endif
  friend void protobuf_AssignDesc_mysqlx_5fconnection_2eproto();
  friend void protobuf_ShutdownFile_mysqlx_5fconnection_2eproto();

  void InitAsDefaultInstance();
  static Close* default_instance_;
};
// ===================================================================


// ===================================================================

// Capability

// required string name = 1;
inline bool Capability::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Capability::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Capability::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Capability::clear_name() {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& Capability::name() const {
  // @@protoc_insertion_point(field_get:Mysqlx.Connection.Capability.name)
  return *name_;
}
inline void Capability::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set:Mysqlx.Connection.Capability.name)
}
inline void Capability::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set_char:Mysqlx.Connection.Capability.name)
}
inline void Capability::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:Mysqlx.Connection.Capability.name)
}
inline ::std::string* Capability::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:Mysqlx.Connection.Capability.name)
  return name_;
}
inline ::std::string* Capability::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Capability::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:Mysqlx.Connection.Capability.name)
}

// required .Mysqlx.Datatypes.Any value = 2;
inline bool Capability::has_value() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Capability::set_has_value() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Capability::clear_has_value() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Capability::clear_value() {
  if (value_ != NULL) value_->::Mysqlx::Datatypes::Any::Clear();
  clear_has_value();
}
inline const ::Mysqlx::Datatypes::Any& Capability::value() const {
  // @@protoc_insertion_point(field_get:Mysqlx.Connection.Capability.value)
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  return value_ != NULL ? *value_ : *default_instance().value_;
#else
  return value_ != NULL ? *value_ : *default_instance_->value_;
#endif
}
inline ::Mysqlx::Datatypes::Any* Capability::mutable_value() {
  set_has_value();
  if (value_ == NULL) value_ = new ::Mysqlx::Datatypes::Any;
  // @@protoc_insertion_point(field_mutable:Mysqlx.Connection.Capability.value)
  return value_;
}
inline ::Mysqlx::Datatypes::Any* Capability::release_value() {
  clear_has_value();
  ::Mysqlx::Datatypes::Any* temp = value_;
  value_ = NULL;
  return temp;
}
inline void Capability::set_allocated_value(::Mysqlx::Datatypes::Any* value) {
  delete value_;
  value_ = value;
  if (value) {
    set_has_value();
  } else {
    clear_has_value();
  }
  // @@protoc_insertion_point(field_set_allocated:Mysqlx.Connection.Capability.value)
}

// -------------------------------------------------------------------

// Capabilities

// repeated .Mysqlx.Connection.Capability capabilities = 1;
inline int Capabilities::capabilities_size() const {
  return capabilities_.size();
}
inline void Capabilities::clear_capabilities() {
  capabilities_.Clear();
}
inline const ::Mysqlx::Connection::Capability& Capabilities::capabilities(int index) const {
  // @@protoc_insertion_point(field_get:Mysqlx.Connection.Capabilities.capabilities)
  return capabilities_.Get(index);
}
inline ::Mysqlx::Connection::Capability* Capabilities::mutable_capabilities(int index) {
  // @@protoc_insertion_point(field_mutable:Mysqlx.Connection.Capabilities.capabilities)
  return capabilities_.Mutable(index);
}
inline ::Mysqlx::Connection::Capability* Capabilities::add_capabilities() {
  // @@protoc_insertion_point(field_add:Mysqlx.Connection.Capabilities.capabilities)
  return capabilities_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Mysqlx::Connection::Capability >&
Capabilities::capabilities() const {
  // @@protoc_insertion_point(field_list:Mysqlx.Connection.Capabilities.capabilities)
  return capabilities_;
}
inline ::google::protobuf::RepeatedPtrField< ::Mysqlx::Connection::Capability >*
Capabilities::mutable_capabilities() {
  // @@protoc_insertion_point(field_mutable_list:Mysqlx.Connection.Capabilities.capabilities)
  return &capabilities_;
}

// -------------------------------------------------------------------

// CapabilitiesGet

// -------------------------------------------------------------------

// CapabilitiesSet

// required .Mysqlx.Connection.Capabilities capabilities = 1;
inline bool CapabilitiesSet::has_capabilities() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CapabilitiesSet::set_has_capabilities() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CapabilitiesSet::clear_has_capabilities() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CapabilitiesSet::clear_capabilities() {
  if (capabilities_ != NULL) capabilities_->::Mysqlx::Connection::Capabilities::Clear();
  clear_has_capabilities();
}
inline const ::Mysqlx::Connection::Capabilities& CapabilitiesSet::capabilities() const {
  // @@protoc_insertion_point(field_get:Mysqlx.Connection.CapabilitiesSet.capabilities)
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  return capabilities_ != NULL ? *capabilities_ : *default_instance().capabilities_;
#else
  return capabilities_ != NULL ? *capabilities_ : *default_instance_->capabilities_;
#endif
}
inline ::Mysqlx::Connection::Capabilities* CapabilitiesSet::mutable_capabilities() {
  set_has_capabilities();
  if (capabilities_ == NULL) capabilities_ = new ::Mysqlx::Connection::Capabilities;
  // @@protoc_insertion_point(field_mutable:Mysqlx.Connection.CapabilitiesSet.capabilities)
  return capabilities_;
}
inline ::Mysqlx::Connection::Capabilities* CapabilitiesSet::release_capabilities() {
  clear_has_capabilities();
  ::Mysqlx::Connection::Capabilities* temp = capabilities_;
  capabilities_ = NULL;
  return temp;
}
inline void CapabilitiesSet::set_allocated_capabilities(::Mysqlx::Connection::Capabilities* capabilities) {
  delete capabilities_;
  capabilities_ = capabilities;
  if (capabilities) {
    set_has_capabilities();
  } else {
    clear_has_capabilities();
  }
  // @@protoc_insertion_point(field_set_allocated:Mysqlx.Connection.CapabilitiesSet.capabilities)
}

// -------------------------------------------------------------------

// Close


// @@protoc_insertion_point(namespace_scope)

}  // namespace Connection
}  // namespace Mysqlx

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_mysqlx_5fconnection_2eproto__INCLUDED
